README.md

[docs] 리드미 최초 업로드

---

test-pjw.js

- [] 새로운 기능 추가
- [] 버그 수정
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
PR 테스트 완료했어서 검토해주세요~
resolves #8

[feat] PR 테스트코드 완료.

---

test-yebin.js

PR 테스트 완료했습니다.

---

test-youngchan.js

- [] 버그 수정
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
resolves #5

✨ feat: test-youngchan

---

src/A13C-chat.ts
src/chat.ts
src/pages/chat.html

[feat] 채팅 구현 중간 push

---

package-lock.json
package.json
src/imges/close-white.svg
src/pages/lobby.html
src/pages/lobby/lobby-scroll.ts
src/pages/lobby/lobby.ts
src/style.css

- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
refs #25

[Feat] 로비 임시 push

---

package-lock.json
package.json
src/pages/ingame.html
src/pages/ingame/ingame.ts
src/style.css

- [] 버그 수정
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
게임 알고리즘 (카드 선택, 초기화, 제출 등)
폴더정리를 위한 중간 푸쉬
resolves #

[feat] ingame.html 중간 푸쉬

---

index.html
src/pages/ingame/chat.ts
src/pages/lobby.html
src/pages/rule.html

[Feat] lobby ksy

---

src/pages/ingame.html
src/pages/ingame/A13C-chat.ts
src/pages/ingame/ingame.ts
src/pages/lobby.html
src/pages/rule.html

ingame에 chat 기능 넣음
resolves #37

[Feat] ingame-ksy

---

index.html
src/pages/ingame.html
src/pages/lobby.html
src/pages/rule.html
src/style.css

반응형 대응과 일반 css 대신 tailwindCSS로 수정함
resolves #48

[Refactor] 반응형과 테일윈드로 수정함

---

src/pages/ingame/A13C-chat.ts
src/pages/ingame/chat.ts
src/pages/ingame/ingame.ts
src/pages/lobby/lobby.ts

[feat] 채팅 인게임과 연동 중간 배포

---

src/pages/ingame.html
src/pages/ingame/ingame.ts

[feat] ingame.html 추가작업

---

src/pages/ingame.html

ingame.html 승점테이블 충돌오류 해결
resolves #

[bug] ingame 충돌 수정

---

src/pages/ingame.html
src/pages/ingame/ingame.ts

[bug] 카드선택 버그 수정 및 8초타이머 세팅

---

src/pages/ingame.html
src/pages/ingame/chat.ts
src/pages/ingame/time-ingame.ts

gamelogic (두개의 카드와 타이머까지)
resolves #

[feat] gamelogic

---

src/components/score-table/score-table.ts

[bugfix] session storage로 변경

---

package.json

package.json 빌드 명령어 수정
resolves #79

[Feat] 빌드 명령어 수정

---

package.json

[Feat] package.json  tsc 명령어 복귀

---

src/pages/ingame/chat.ts

[fix] 채팅 입퇴장 메시지 수정완료

---

src/pages/ingame.html
src/pages/ingame/chat.ts
src/pages/ingame/ingame-server.ts

[bug] 상대 닉네임 오류 (진행중)

---

src/pages/ingame/round-and-ranking.ts

- 매라운드 종료 시 라운드 하나 증가
- 누적승점을 통해 5라운드가 종료되면 최종순위 발표(모달)
resolves #74

[feat] round증가 및 최종순위 표시

---

src/pages/ingame/round-and-ranking.ts

- 매 라운드 종료 후 승자 표시되는 함수 제거
- 라운드 마다 업데이트 되는 함수 제거
resolves #101

[fix]round-and-ranking파일 중복 구현 수정완료

---

src/pages/ingame/A13C-chat.ts
src/pages/ingame/chat.ts

- 채팅방에 참여인원이 없으면 자동 삭제 (autoClose 추가)
resolves #105

[feat] 채팅에 autoClose 추가

---

src/components/score-table/round/round-table.ts
src/pages/ingame.html

[feat] 라운드 테이블 추가

---

src/script/ingame/index.ts

- index.ts 파일 내 오류 수정 (괄호 문제)
resolves #124

[fix] index.ts 오류 수정 완료

---

src/script/lobby/join-room-modal.ts

[fix] 게임시작창 수정 (참여할때 로컬스토리지 set)
resolves #

[fix] 게임시작창 수정 (참여할때 로컬스토리지 set)

---

src/pages/ingame.html
src/script/ingame/ingame-ui.ts
src/script/ingame/round-start.ts

[TODO] 중간 커밋

---

src/script/ingame/round-table.ts

[feat] 라운드 테이블 함수 추가

---

src/pages/ingame.html

[fix] timer 삭제

---

src/script/ingame/chat.ts
src/script/ingame/index.ts

[fix]chat-count

---

src/script/ingame/chat.ts
src/script/ingame/index.ts
src/script/ingame/ingame-ui.ts

[bug] 중간 커밋

---

src/pages/ingame.html
src/script/ingame/index.ts
src/script/ingame/ingame-ui.ts
src/script/ingame/round-start.ts
src/script/ingame/round-table.ts

[bug] 라운드 테이블
